"use strict";
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeTree = void 0;
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
const __root_1 = require("./routes/__root");
const _sitebody_1 = require("./routes/_sitebody");
const index_1 = require("./routes/index");
const why_1 = require("./routes/_sitebody/why");
const services_1 = require("./routes/_sitebody/services");
const about_1 = require("./routes/_sitebody/about");
const SitebodyRoute = _sitebody_1.Route.update({
    id: '/_sitebody',
    getParentRoute: () => __root_1.Route,
});
const IndexRoute = index_1.Route.update({
    id: '/',
    path: '/',
    getParentRoute: () => __root_1.Route,
});
const SitebodyWhyRoute = why_1.Route.update({
    id: '/why',
    path: '/why',
    getParentRoute: () => SitebodyRoute,
});
const SitebodyServicesRoute = services_1.Route.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => SitebodyRoute,
});
const SitebodyAboutRoute = about_1.Route.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => SitebodyRoute,
});
const SitebodyRouteChildren = {
    SitebodyAboutRoute: SitebodyAboutRoute,
    SitebodyServicesRoute: SitebodyServicesRoute,
    SitebodyWhyRoute: SitebodyWhyRoute,
};
const SitebodyRouteWithChildren = SitebodyRoute._addFileChildren(SitebodyRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    SitebodyRoute: SitebodyRouteWithChildren,
};
exports.routeTree = __root_1.Route
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
